# Generated by Django 2.1.7 on 2019-03-01 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Headline', models.CharField(default='no headline', max_length=1000)),
                ('SentimentScore', models.IntegerField()),
                ('Sentiment', models.CharField(max_length=100)),
                ('Source', models.CharField(default='no source', max_length=200)),
                ('SourceURL', models.URLField(default='https://google.com')),
            ],
        ),
    ]
