# Generated by Django 2.1.7 on 2019-03-02 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adpricing', '0002_auto_20190302_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addata',
            name='language',
            field=models.CharField(choices=[('1', 'English'), ('2', 'Hindi'), ('3', 'Punjabi'), ('4', 'Urdu'), ('5', 'Marathi'), ('6', 'Others')], default=6, max_length=1),
        ),
    ]
