# Generated by Django 2.0.7 on 2019-03-01 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdPriceAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspaper_data',
            name='Marks',
            field=models.BooleanField(default='True'),
        ),
        migrations.AddField(
            model_name='newspaper_data',
            name='RegularityStatus',
            field=models.BooleanField(default='True'),
        ),
    ]
