# Generated by Django 2.0.7 on 2019-03-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdPriceAPI', '0003_auto_20190301_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspaper_data',
            name='CirculationScore',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
