# Generated by Django 2.0.7 on 2019-02-16 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NEWS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SNo', models.IntegerField()),
                ('Datetime', models.DateTimeField()),
                ('News', models.TextField()),
                ('Sentiments', models.TextField()),
                ('Senscore', models.IntegerField()),
            ],
        ),
    ]
