# Generated by Django 2.0.7 on 2019-02-16 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storecsv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='reference',
            field=models.TextField(default='Times Of India'),
        ),
        migrations.AddField(
            model_name='news',
            name='urlchahiye',
            field=models.URLField(default='https://docs.djangoproject.com/en/2.1/ref/models/fields/'),
        ),
    ]
